// api/leaderboard.js
export default function handler(req, res) {
  try {
    const { type = 'goals', data = 'Player1+10+Player2+5' } = req.query;
    
    // Parse data
    const parts = data.split('+');
    const players = [];
    
    for (let i = 0; i < parts.length; i += 2) {
      if (i + 1 < parts.length) {
        players.push({
          name: parts[i],
          score: parseInt(parts[i + 1]) || 0
        });
      }
    }
    
    // Sort players by score (highest first)
    players.sort((a, b) => b.score - a.score);
    
    // Create SVG
    const width = 600;
    const height = 150 + players.length * 60;
    
    let svg = '<svg width="' + width + '" height="' + height + '" xmlns="http://www.w3.org/2000/svg">';
    
    // Background gradient
    svg += '<defs>';
    svg += '<linearGradient id="bg" x1="0%" y1="0%" x2="0%" y2="100%">';
    svg += '<stop offset="0%" style="stop-color:#667eea;stop-opacity:1" />';
    svg += '<stop offset="100%" style="stop-color:#764ba2;stop-opacity:1" />';
    svg += '</linearGradient>';
    svg += '</defs>';
    
    svg += '<rect width="' + width + '" height="' + height + '" fill="url(#bg)"/>';
    
    // Title
    svg += '<text x="' + (width/2) + '" y="50" font-family="Arial" font-size="32" font-weight="bold" fill="white" text-anchor="middle">';
    svg += type.toUpperCase() + ' LEADERBOARD';
    svg += '</text>';
    
    // Players
    players.forEach(function(player, index) {
      const y = 120 + index * 60;
      const position = index + 1;
      let badgeColor = '#FFD700'; // Gold
      if (position === 2) badgeColor = '#C0C0C0'; // Silver  
      if (position === 3) badgeColor = '#CD7F32'; // Bronze
      if (position > 3) badgeColor = '#4A5568'; // Gray
      
      // Position badge
      svg += '<circle cx="50" cy="' + y + '" r="20" fill="' + badgeColor + '"/>';
      svg += '<text x="50" y="' + (y + 5) + '" font-family="Arial" font-size="16" font-weight="bold" fill="black" text-anchor="middle">' + position + '</text>';
      
      // Name
      svg += '<text x="90" y="' + (y + 8) + '" font-family="Arial" font-size="24" font-weight="bold" fill="white">' + player.name + '</text>';
      
      // Score  
      svg += '<text x="' + (width - 40) + '" y="' + (y + 8) + '" font-family="Arial" font-size="28" font-weight="bold" fill="#FFE135" text-anchor="end">' + player.score + '</text>';
      
      // Separator line
      if (index < players.length - 1) {
        svg += '<line x1="40" y1="' + (y + 30) + '" x2="' + (width - 40) + '" y2="' + (y + 30) + '" stroke="rgba(255,255,255,0.2)" stroke-width="1"/>';
      }
    });
    
    // Footer
    svg += '<text x="' + (width/2) + '" y="' + (height - 20) + '" font-family="Arial" font-size="14" fill="rgba(255,255,255,0.5)" text-anchor="middle">Generated by Discord Bot</text>';
    
    svg += '</svg>';
    
    res.setHeader('Content-Type', 'image/svg+xml');
    res.setHeader('Cache-Control', 'public, max-age=3600');
    res.status(200).send(svg);
    
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
}
